### PR TITLE
Add energy consumption entities

### LINKED ISSUE #103: Feature request: Support energy monitoring features of home assistant 2021.8
In the as I'm writing latest Home Assistant-release, there's an energy dashboard (https://www.home-assistant.io/blog/2021/08/04/home-energy-management/).

It would be nice if relevant sensors could be added as individual devices.

### PR DESCRIPTION
**Pull request by wilfredktlr**
Fixes #103.

### CODE REVIEW

**Comment by bstenborg** [comment]
Great change! Started measuring total power consumption and solar production recently so this is a great addition. However, no entities are showing up in HA - is there anything special that needs to be done? I was expecting e.g. "heating, int. add. incl.". If it's any indication, I cannot see any energy consumption numbers on the Nibe Uplink Serviceinfo page either.

**Comment by elupus** [comment]
> Great change! Started measuring total power consumption and solar production recently so this is a great addition. However, no entities are showing up in HA - is there anything special that needs to be done? I was expecting e.g. "heating, int. add. incl.". If it's any indication, I cannot see any energy consumption numbers on the Nibe Uplink Serviceinfo page either.

Do you actually have an external energy meter cpnnected to your pump?

**Comment by bstenborg** [comment]
Oh, I thought it had internal measurement. No, but it was delivered with three power clamps that the installer said were superfluous. I guess I can just clamp them on the supply cable leads. Will look through the installation guide.

**Comment by bstenborg** [comment]
Hm, the way I read it the supplied power measurement clamps are to be installed on the incoming power supply to the house, so that the pump can choose to draw power from the most lightly loaded phase. This of course cannot be used for measuring the power consumption of the heat pump itself. I find no other mention of power measurement in the installation guide.

**Comment by elupus** [comment]
Yup, the clamps are for load controls. You need a fully separate meter with pulse output, that can then be connected to the pump. It support pulse input on one of its aux inputs. Yes its somewhat silly. This is even mandated to be installed in some countries.

**Comment by bstenborg** [comment]
The installation manual for my F1255 doesn't list power measurement as one of the possible uses of the AUX inputs, neither is there such an accessory listed on their home page for this model. Maybe only compatible with other models. Which one are you using? A shame. I could just as well get an external Z-Wave tree phase power monitor (though those aren't exactly cheap), but I really liked the idea of being able to separate energy use for heating, water and pool, which I guess may be possible but would be way harder to accomplish with a completely separate monitor.

**Comment by frli4797** [comment]
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/nibe/switch.py:75 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 20:07:03 (1 occurrences) 
Last logged: 20:07:03

[547660718976] FORMAT_ERROR: Input format error. {'httpStatusCode': 400, 'errorCode': 1, 'timestamp': '2022-09-09T18:07:03.8070734Z', 'details': ['Error 14: 48043'], 'data': None}
aiohttp.client_exceptions.ClientResponseError: 400, message="{'httpStatusCode': 400, 'errorCode': 1, 'timestamp': '2022-09-09T18:07:03.8070734Z', 'details': ['Error 14:  48043'], 'data': None}", url=URL('https://api.nibeuplink.com/api/v1/systems/46893/parameters')

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1738, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1775, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 931, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/config/custom_components/nibe/switch.py", line 75, in async_turn_on
    await self._uplink.put_parameter(self._system_id, self._parameter_id, "1")
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/uplink.py", line 176, in put_parameter
    result = await self.put(
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/uplink.py", line 87, in put
    return await self.session.request(
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 186, in request
    await raise_for_status(response)
  File "/usr/local/lib/python3.10/site-packages/nibeuplink/session.py", line 26, in raise_for_status
    raise UplinkResponseException(data.get("errorCode"), data) from e
nibeuplink.exceptions.UplinkResponseException: FORMAT_ERROR: Input format error.
{'httpStatusCode': 400, 'errorCode': 1, 'timestamp': '2022-09-09T18:07:03.8070734Z', 'details': ['Error 14:  48043'], 'data': None}
```

**Comment by atoikka** [comment]
@bstenborg look up terminals AA3-X22/23 in your manual, these are for external pulses from energy meters.

My own setup actually uses the clamps for measuring the current of only the pump supply. This gives a decent indication of what the F1255 pump is doing, but I have not created an accumulating kWh entity, because it would be inaccurate due to low refresh rate (compared to the multiple-times-per-second of Shelly 3EM) and I would not know the exact power factor.
image

For accurate monitoring, another option is the Modbus card, but that's well priced compared to Shelly 3EM, for example. If I'm not mistaken, some pumps like S1255 have local modbus support built in, that would allow live data reading.

**Comment by bstenborg** [comment]
Thanks for your response atoikka! But I'm even more confused now. 😂

The installation manual for the F1255 that I downloaded from Nibe doesn't mention AA3-X22/23 at all. It says that the bundled power clamps should be connected to AA3-X4, but again, connecting them to the house incoming power supply only helps with load balancing, not measuring the pump consumption.

I can't find anything in the manual about measuring the pump consumption, nor connecting anything for this purpose. No such accessory or AUX input is mentioned.

I can of course just add external measurement, but I was really looking for a way to differentiate between power spent on heating, warm water and pool (yes, I'm using the pool accessory). So I either need to get the consumption numbers out from the pump, or conceivably get the current operating mode out continuously and do the splitting in home assistent, but I'm afraid this will be error prone.

**Pull request merged**
